id(token) = /[a-z]+/;

tk(token) = 'tok';

ids = tk:tk l:id r:id;

arg = ',' id;

args = id {arg};

call = tk:tk lp:'(' first:id rest:{arg} rp:')';

pos = {id:id}+ [tk];

poswrap = tk:tk ':' [clos:pos];

ws = tk:tk ':' [args:args];

# FIXME error
list = tk ':' [pos];

stats = lb:'{' head:call tail:{/\n/ call} rb:'}';
